[package]
name = "TSPL"
version = "0.0.8"
authors = ["Victor Taelin <victor.taelin@gmail.com>"]
edition = "2021"
description = "The Simplest Parser Library"
repository = "https://github.com/HigherOrderCO/TSPL"
license = "MIT"

[dependencies]
highlight_error = "0.1.1"
